package scanner;

/**
 * @author nikaylahwoody
 *
 */
public enum TokenType {
	
	AND, ARRAY, BEGIN,  DIV, DO,  //KEYWORDS
	
	
	ID, NUMBER, //TYPES
	
	//SYMBOLS
	SEMICOLON, COMMA, PERIOD, COLON, LEFTBRACE, RIGHTBRACE, LEFTPARA, RIGHTPARA, PLUS, MINUS, EQUAL, ASSIGN, DIAMOND, LESSTHAN, LESSTHANEQUAL, GREATERTHAN, GREATERTHANEQUAL, ASTERISK
}
